// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class FlyScript : MonoBehaviour 
{
	private float heightTest = 3f;
	void Start ()
	{
		Debug.Log (transform.position.y);
		if (transform.position.y <= heightTest) 
		{
			Debug.Log ("I'm about to hit the ground!");
			FlyAway ();
		} else if (transform.position.y >= heightTest) 
		{
			Debug.Log ("I'm flying!");
		}
	}
	//hello


	private void FlyAway()
	{
		Debug.Log("Fly Away!");
		Vector3 newPosition = new Vector3(0,7,0);
		transform.position = newPosition;
	}
	/*this
	 * is 
	 * multiple lines
	 * */
}